targets: 
  $default:
    sources:
      - $package$
      - example/**
      - lib/**
    builders:
      flavorz|flavorBuilder:
        enabled: true

builders:
  flavorBuilder:
    import: 'package:flavorz/flavorz.dart'
    builder_factories: ['build']
    build_extensions: {'.json': ['.dart']}
    build_to: source
    auto_apply: dependents
