name: flavorz
description: "Different Environments For Your Application, With Pure Dart"
version: 1.0.0
homepage: https://github.com/AymanProjects/dart-flavorz

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.3.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0