name: flavorz
description: "Generate Different Environments For Your Application From A Single Json File. With Pure Dart."
version: 1.0.5
repository: https://github.com/AymanProjects/dart-flavorz
issue_tracker: https://github.com/AymanProjects/flutter-flavorz/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  build_test: ^2.1.5